### ISSUE TITLE
Docs multiversion availability

### ISSUE THREAD

**Issue by calvellido** [arrow-kt/arrow#1298]
Right now only one version/edition of the docs is available, which is aimed at latest Arrow snapshot.

We need to have different versions available (v0.8.2, v0.9.0...), so users can check the docs for that specific release when something changes over time in the library.

- [x] Create AWS EC2 instances for the different arrow versions https://github.com/47deg/try.arrow-kt.io/issues/41
- [x] Create AWS S3 buckets for for the different arrow docs versions https://github.com/47deg/try.arrow-kt.io/issues/42
- [x] Create needed subdomains for new Try Arrow instances, and point them to their appropriate instances https://github.com/47deg/try.arrow-kt.io/issues/46
- [x] Automate SSL cert creation inside a new instance https://github.com/47deg/try.arrow-kt.io/issues/43
- [ ] Automate SSL cert renewal https://github.com/47deg/try.arrow-kt.io/issues/40
- [x] Deploy tryArrow in each instance for the appropriate arrow version https://github.com/47deg/try.arrow-kt.io/issues/44
- [x] Deploy the docs in each bucket for the appropriate arrow version https://github.com/47deg/try.arrow-kt.io/issues/45
- [ ] Create needed Amazon Cloudfront distributions for each new docs URL, pointing them to their appropriate instances (done for https://0-8-2.arrow-kt.io)
- [x] Connect each deployed arrow docs with its appropriate instance
- [ ] Modify the arrow docs website to allow to choose between the different arrow docs versions https://github.com/arrow-kt/arrow/issues/1309

**Comment by calvellido** [comment]
To complete this, and to be able to keep using Arrow Playground snippets properly, we might need to get this done first:

https://github.com/47deg/try.arrow-kt.io/issues/40

**Comment by rachelcarmena** [comment]
Please @calvellido , could we close this issue? Thanks!!

**Comment by calvellido** [comment]
Yes, this was accomplished!  Thanks @rachelcarmena :raised_hands:

**Comment by rachelcarmena** [comment]
> Yes, this was accomplished! Thanks @rachelcarmena raised_hands

Thanks to youuu!! :raised_hands:
