### ISSUE TITLE
[EPIC] - Arrow FX Benchmarks

### ISSUE THREAD

**Issue by fedefernandez** [arrow-kt/arrow#1299]
Using jmh we want to port the [cats-effect](https://github.com/typelevel/cats-effect/tree/master/benchmarks) and [zio](https://github.com/scalaz/scalaz-zio/tree/master/benchmarks/src/main/scala/scalaz/zio) benchmarks to Arrow FX. This needs to be done in several tasks:

* [x] Create a new module in arrow for holding the benchmarks
* [x] Migrate the cats-effect benchmarks
* [x] Migrate de zio benchmarks

**Comment by JorgeCastilloPrz** [comment]
I believe this is part of our work over Fx @raulraja @nomisRev ? Let me know if I'm wrong. I'm organizing goals a bit in 47 and wanna keep track of what's done / to be done around Fx for this quarter.

**Comment by raulraja** [comment]
yes, though all the tasks @fedefernandez and @AdrianRaFo were working with related to Fx Benchmarks are already completed, it's just Simon and me for now improving the benchmarks and Fx stack safety as we go over the benchmarks.

**Comment by JorgeCastilloPrz** [comment]
Sounds good, thanks.
