### ISSUE TITLE
Release 0.9.1

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1422]
- [ ] Add top-level packages that include -data and -extension
- [x] Rename `fx` interfaces to something consistent #1435 
- [x] `Fx` extensions for Rx #1427
- [ ] `Fx` extensions for Reactor #1281 
- [x] Deprecate `delay` in MonadDefer and replace with `effect`
- [x] Remove deprecations #1424
- [x] Deprecate PartialFunction (#1419) (#1423)
- [x] Fix ParTraverse #1414 
- [ ] Update maven badges
- [X] Update some docs: #1421 

@nomisRev 

- [x] Fix to correct use of `Sequence` in KotlinTest for laws
- [x] Fix Resource's stack safety

**Comment by i-walker** [comment]
@pakoito can we close this?

**Comment by pakoito** [comment]
Yep!
