### ISSUE TITLE
New module: arrow-android

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#1452]
Let's collect some ideas and features. 

@arrow-kt/maintainers Feel free to comment or edit this post to add/edit/fix anything you consider :+1: 

- [ ] Provide Android's main coroutine context
- [ ] Create explicit `evalOnMain` extension function based on future's `evalOn` (see #1394)
- [ ] Check how Proguard affects Arrow and provide any necessary proguard rules through gradle's `consumerProguardFiles` (see #1406)
- [ ] Update Arrow's Google samples repo with this module (see #454)
- [ ] Explore possibilities of an arrow-like ["declarative toolkit for building UI" such as Google's compose](https://developer.android.com/jetpack/compose/)
