### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#69]
# Roadmap

## data

- [x] Option
- [x] Try
- [x] Either
- [x] Ior
- [x] Coproduct
- [x] Free
- [x] Cofree #92 
- [x] Trampoline #77 
- [x] Coyoneda #80 
- [x] FreeApplicative #164
- [x] NonEmptyList
- [ ] Vector #97
- [ ] NonEmptyVector #96 
- [x] OptionT
- [x] StateT #14 
- [x] WriterT #84
- [x] EitherT
- [x] Kleisli
- [x] Cokleisli #86
- [x] Function0 #95 
- [x] Function1 #137
- [x] PartialFunction + case syntax #143

## typeclasses

- [x] Functor (improved by #173)
- [x] FunctorFilter #224
- [x] Applicative
- [x] ApplicativeError
- [x] Monad
- [x] MonadError
- [x] MonadCombine (#248 Work in progress)
- [x] MonadFilter #242
- [x] MonadReader
- [x] MonadState #145
- [x] MonadWriter #210
- [x] Semigroup
- [x] SemigroupK #149
- [x] Monoid
- [x] MonoidK #151
- [x] Foldable
- [x] Traverse
- [x] Reducible #215
- [x] TraverseFilter (#255 Work In Progress)
- [x] Inject 
- [x] FunctionK
- [ ] Choice

## instances

- [x] all instances of typeclasses that can be applied over defined datatypes and those from the kotlin stdlib

## syntaxis

- [x] syntax for all types which in some way implement a typeclass either directly or through companion.
- [x] tuple destructuring #99

## utils

- [x] monadic comprehensions
- [x] comonadic comprehensions #88
- [x] cartesian builder
- [x] find a way to register implicit typeclasses with arity 2+

## tests

- [x] discipline #65
- [x] missing traverse laws #136

## docs

- [ ] Docs for each data type and type class including example use cases

**Comment by pakoito** [comment]
Are we going to do Fix and the XXXmorphisms from recursion schemes?

**Comment by pakoito** [comment]
I would also add Task, even if it's just a compositin of the others, or a separate project altogether (?).

**Comment by raulraja** [comment]
@pakoito yes we can do that but it's not strictly necessary for the first version, I guess we should add it and label everything with the version we expect it to come out

**Comment by raulraja** [comment]
Let's add Task I also want to add Lenses but those don't need to be in a first version either.

**Comment by pakoito** [comment]
`followedBy` y `forEffect`

[21:56] 
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/FlatMap.scala#L48 (edited)

[21:56] 
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/FlatMap.scala#L70 (edited)

[21:57] 
y hay variaciones para Eval de los mismos

**Comment by pakoito** [comment]
ifM

**Comment by pakoito** [comment]
Complete Functor https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Functor.scala

**Comment by pakoito** [comment]
Composed instances

https://github.com/FineCinnamon/Katz/issues/104

**Comment by pakoito** [comment]
Add MonadTrans. 

Resources:
https://ro-che.info/articles/2014-07-15-type-based-lift
 https://github.com/typelevel/cats/pull/844

**Comment by pakoito** [comment]
More suggestions: https://wiki.haskell.org/Monad#Interesting_monads

**Comment by pakoito** [comment]
Nested: https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/Nested.scala

And the traverse law that requires Nested: https://github.com/typelevel/cats/blob/master/laws/src/main/scala/cats/laws/TraverseLaws.scala#L16

**Comment by pakoito** [comment]
Category and MonoidK typeclasses

https://github.com/kategory/kategory/pull/137#discussion_r128702625

**Comment by pakoito** [comment]
MonadReader laws

https://github.com/kategory/kategory/pull/137#discussion_r128701632

**Comment by pakoito** [comment]
Easy

binding tests for monad and comonad

https://github.com/kategory/kategory/pull/137/files/b323cc6f139ed589150f7ee59c9c3878c5895262#r128701973

**Comment by pakoito** [comment]
Improve free with resume, fold...

**Comment by pakoito** [comment]
Except/ExceptT

https://hackage.haskell.org/package/transformers-0.5.4.0/docs/src/Control.Monad.Trans.Except.html#


Inspired by

https://twitter.com/daniel_mbfm/status/888890585318391810

**Comment by pakoito** [comment]
Adjunction: https://www.youtube.com/watch?v=BLk4DlNZkL8

Should be easy to implement.

**Comment by pakoito** [comment]
AsyncContext from FreeStyle:

https://github.com/frees-io/freestyle/blob/master/freestyle-async/async/shared/src/main/scala/async.scala

**Comment by raulraja** [comment]
Thanks to everyone that helped here! closing this old issue now 🙏
